import { StyleSheet, Platform } from 'react-native';

export const ModelStyles = StyleSheet.create({
    // ... (Your original ModelStyles here)
    container: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        zIndex: 15,
    },
    statusBox: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        backgroundColor: 'rgba(50, 205, 50, 0.8)',
        borderRadius: 8,
        position: 'absolute',
        top: '10%',
        zIndex: 20,
    },
    statusText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 5,
    },
    modelViewer: {
        width: '90%',
        height: '40%',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#32CD32',
        marginBottom: 10,
    },
    modelText: { /* ... */ },
    detailsBox: {
        width: '90%',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        padding: 15,
        borderRadius: 8,
    },
    modelDetailsTitle: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    modelDetails: {
        color: '#B0B0B0',
        fontSize: 12,
        marginBottom: 2,
    },
    responseText: {
        color: '#87CEEB',
        fontSize: 10,
        fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    },
    clearButton: {
        position: 'absolute',
        bottom: 20,
        padding: 12,
        backgroundColor: '#FF6347',
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 3,
        elevation: 5,
    },
    clearButtonText: {
        color: '#FFF',
        marginLeft: 8,
        fontWeight: 'bold',
        fontSize: 16,
    }
});

export const styles = StyleSheet.create({
    // ... (Your original general styles here)
    container: {
        flex: 1,
        backgroundColor: '#000',
    },

    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#1E1E1E',
    },
    loadingText: {
        marginTop: 20,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFF',
    },
    loadingSubText: {
        marginTop: 5,
        fontSize: 14,
        color: '#A9A9A9',
    },
    // ... (rest of the styles)
    permissionsContainer: { /* ... */ },
    permissionsTitle: { /* ... */ },
    permissionsText: { /* ... */ },
    permissionsButtons: { /* ... */ },
    permissionsButton: { /* ... */ },
    permissionsButtonText: { /* ... */ },
    linkText: { /* ... */ },
    cameraPreview: {
        flex: 1,
    },
    topControlBar: {
        height: Platform.OS === 'ios' ? 100 : 80,
        backgroundColor: '#111',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: Platform.OS === 'ios' ? 40 : 20,
        paddingHorizontal: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#333',
    },
    topBarTitle: {
        color: '#FFF',
        fontSize: 18,
        fontWeight: 'bold',
    },
    backButton: {
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 20,
        padding: 8,
    },
    spacer: {
        width: 56,
    },
    zoomTextOverlay: {
        position: 'absolute',
        bottom: 140,
        left: 0,
        right: 0,
        alignItems: 'center',
        paddingVertical: 5,
        backgroundColor: 'rgba(0,0,0,0.5)',
        zIndex: 10,
    },
    zoomText: {
        color: '#FFF',
        fontSize: 14,
    },
    bottomControlBar: {
        height: 140,
        backgroundColor: '#111',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 30,
        paddingBottom: 40,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#333',
    },
    bottomControlBarThreeButtons: {
        height: 140,
        backgroundColor: '#111',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
        paddingBottom: 40,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#333',
    },
    flipButton: {
        width: 56,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 28,
    },
    captureButton: {
        width: 80,
        height: 80,
        borderRadius: 40,
        borderWidth: 6,
        borderColor: '#FFFFFF',
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    captureInnerCircle: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#FFFFFF',
    },
    previewImageFlexContainer: {
        flex: 1,
        position: 'relative',
        backgroundColor: '#000',
    },
    previewImageFull: {
        ...StyleSheet.absoluteFillObject,
        width: '100%',
        height: '100%',
    },
    locationTagHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 15,
        paddingVertical: 6,
        paddingHorizontal: 12,
    },
    locationTextHeader: {
        color: '#FFF',
        fontSize: 14,
        marginLeft: 5,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 10,
        minWidth: '31%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 8,
        marginHorizontal: 5,
    },
    retakeButton: {
        backgroundColor: '#FF6347',
    },
    sendButton: {
        backgroundColor: '#32CD32',
    },
    sendWithoutLocationButton: {
        backgroundColor: '#FFA500',
    },
    cropButton: {
        backgroundColor: '#FFA500',
    },
    sendButtonDisabled: {
        backgroundColor: 'rgba(50, 205, 50, 0.5)',
    },
    actionButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '700',
        marginLeft: 5,
        textAlign: 'center',
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 11,
    },
    overlayText: {
        color: '#FFF',
        marginTop: 10,
        fontSize: 16,
    }
});